### ISSUE TITLE
Game Request: Mass Effect Legendary Edition 

### ISSUE THREAD

**Issue by Patchier** [wabbajack-tools/indexed-game-files#10]

**Comment by EzioTheDeadPoet** [comment]
The wrong repository for where I can work on this but I will still keep it in mind.👍

**Comment by Patchier** [comment]
> The wrong repository for where I can work on this but I will still keep it in mind.👍

I took a guess Luca. ;w;

**Comment by EzioTheDeadPoet** [comment]
While tying to add support today when updating the gamefinder library I sadly realized that MO2 dropped support for ME:LE due to MO2 not working correctly with it.
So it is unlikely that ME:LE support for WJ will ever happen.
Dragon Age Origins and Dragon Age Inquisition should work in the next update when installed via the EA Desktop App (and steam/gog, excluding the possible issues with different game versions on the different stores).
